### ISSUE TITLE
Embedding failed: input is too large to process, please increase the physical batch size

### ISSUE THREAD

**Issue by linyinli** [gpustack/gpustack#472] opened 2024-10-25 07:43 UTC
**Describe the bug**
Embedding failed:
```
0.17.040.446 E srv                 send_error: task id = 12, error: input is too large to process, please increase the physical batch size
0.17.040.488 I srv         log_server_request: request 500: POST /v1/embeddings 192.168.50.4:6038
```

The model’s max context length is 512, but GPUStack set --ctx-size to 8192.

llama-box process:
```
/Users/seal/.local/pipx/venvs/gpustack/lib/python3.12/site-packages/gpustack/third_party/bin/llama-box/llama-box --host 0.0.0.0 --embeddings --gpu-layers 13 --parallel 4 --ctx-size 8192 --port 40895 --model /var/lib/gpustack/cache/huggingface/models--CompendiumLabs--bge-base-en-v1.5-gguf/snapshots/24914efdfa9ee54e815c3fcaa78a617031251c5c/./bge-base-en-v1.5-f16.gguf --no-mmap --ctx-size 512 --parallel 1 --batch-size 512 --ubatch-size 512
```

**Steps to reproduce**

1. Create an embedding model;
2. Using Dify to test embedding;

**Expected behavior**

Embedding succeed.

**Environment**

- GPUStack version: 0.3.1rc1 ( llama-box v0.0.70 )
- OS: macos
- GPU: M2 Ultra

**Comment by thxCode** [comment] 2024-10-25 11:46
This is a reasonable error as the embedding model cannot process a prompt in which tokens exceed the context size its trained.

When this error happens, you should reduce the cutting size of the document.

**Comment by Finenyaco** [comment] 2024-10-25 13:36
Closed as not a bug

**Closed by Finenyaco** 2024-10-25 13:36 UTC
Labels: bug-qa
