### ISSUE TITLE
Missing GPUs after installing GPUStack  with containers

### ISSUE THREAD

**Issue by Finenyaco** [gpustack/gpustack#450] opened 2024-10-24 06:33 UTC
**Describe the bug**

**Steps to reproduce**

1. Run `docker run -d --gpus all -p 8088:80 gpustack/gpustack:main`.
2. Check the worker list.

**Result**

1. No GPU shown.
<img width="2304" alt="image" src="https://github.com/user-attachments/assets/8afd3b9b-9c07-4a66-aac9-972f93233722">

```
2024-10-24T06:25:06+00:00 - gpustack.server.server - INFO - Starting GPUStack server.
2024-10-24T06:25:06+00:00 - gpustack.server.server - INFO - Running database migration.
2024-10-24T06:25:06+00:00 - gpustack.server.server - INFO - Database migration completed.
2024-10-24T06:25:06+00:00 - gpustack.server.server - INFO - Generated initial admin password. You can get it from /var/lib/gpustack/initial_admin_password.
2024-10-24T06:25:06+00:00 - gpustack.server.server - INFO - Serving on 0.0.0.0:80.
2024-10-24T06:25:06+00:00 - gpustack.scheduler.scheduler - INFO - Scheduler started.
2024-10-24T06:25:07+00:00 - gpustack.worker.tools_manager - INFO - downloading llama-box-linux-amd64-cuda-12.4 'v0.0.67'
2024-10-24T06:25:19+00:00 - gpustack.worker.tools_manager - INFO - downloading gguf-parser-linux-amd64 'v0.12.0'
2024-10-24T06:25:21+00:00 - gpustack.worker.tools_manager - INFO - downloading fastfetch-linux-amd64 '2.25.0.1'
2024-10-24T06:25:23+00:00 - gpustack.worker.worker - INFO - Starting GPUStack worker.
2024-10-24T06:25:23+00:00 - gpustack.worker.worker - INFO - Serving worker APIs on 0.0.0.0:10150.
2024-10-24T06:25:23+00:00 - gpustack.worker.worker_manager - INFO - Started RPC server for GPU 1 on port 50918, pid 106
2024-10-24T06:25:23+00:00 - gpustack.worker.rpc_server - INFO - Starting llama-box rpc server
2024-10-24T06:25:23+00:00 - gpustack.worker.worker_manager - INFO - Started RPC server for GPU 0 on port 50565, pid 108
2024-10-24T06:25:23+00:00 - gpustack.worker.rpc_server - INFO - Starting llama-box rpc server
2024-10-24T06:25:23+00:00 - gpustack.worker.worker_manager - INFO - Registering worker: 2a67952286d9
2024-10-24T06:25:23+00:00 - gpustack.worker.worker_manager - INFO - Worker 2a67952286d9 registered.
2024-10-24T06:25:23+00:00 - gpustack.worker.exporter - INFO - Serving metric exporter on 0.0.0.0:10151.
```

**Expected behavior**

**Environment**

- GPUStack version: main 29e1c0c
- OS: Ubuntu 22.04
- GPU: NVIDIA GeForce RTX 4080 * 2

**Additional context**

Run fastfetch manually.
```
[
  {
    "type": "Title",
    "result": {
      "userName": "root",
      "hostName": "2a67952286d9",
      "homeDir": "/root/",
      "exePath": "/usr/local/lib/python3.10/dist-packages/gpustack/third_party/bin/fastfetch/fastfetch",
      "userShell": "/bin/bash"
    }
  },
  {
    "type": "Separator",
    "error": "Unsupported for JSON format"
  },
  {
    "type": "OS",
    "result": {
      "buildID": "",
      "codename": "jammy",
      "id": "ubuntu",
      "idLike": "debian",
      "name": "Ubuntu",
      "prettyName": "Ubuntu 22.04.4 LTS",
      "variant": "",
      "variantID": "",
      "version": "22.04.4 LTS (Jammy Jellyfish)",
      "versionID": "22.04"
    }
  },
  {
    "type": "Host",
    "error": "neither product_family nor product_name is set by O.E.M."
  },
  {
    "type": "Kernel",
    "result": {
      "architecture": "x86_64",
      "name": "Linux",
      "release": "6.8.0-47-generic",
      "version": "#47~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Wed Oct  2 16:16:55 UTC 2",
      "displayVersion": "",
      "pageSize": 4096
    }
  },
  {
    "type": "Uptime",
    "result": {
      "uptime": 89131270,
      "bootTime": "2024-10-23T05:43:09.799+0000"
    }
  },
  {
    "type": "Packages",
    "result": {
      "all": 254,
      "apk": 0,
      "brew": 0,
      "brewCask": 0,
      "choco": 0,
      "dpkg": 254,
      "emerge": 0,
      "eopkg": 0,
      "flatpakSystem": 0,
      "flatpakUser": 0,
      "nixDefault": 0,
      "nixSystem": 0,
      "nixUser": 0,
      "pacman": 0,
      "paludis": 0,
      "pkg": 0,
      "pkgtool": 0,
      "macports": 0,
      "rpm": 0,
      "scoop": 0,
      "snap": 0,
      "winget": 0,
      "xbps": 0,
      "opkg": 0,
      "am": 0,
      "sorcery": 0,
      "guixSystem": 0,
      "guixUser": 0,
      "guixHome": 0,
      "linglong": 0,
      "pacstall": 0,
      "pacmanBranch": ""
    }
  },
  {
    "type": "Shell",
    "result": {
      "exe": "bash",
      "exeName": "bash",
      "exePath": "/usr/bin/bash",
      "pid": 175,
      "ppid": 0,
      "processName": "bash",
      "prettyName": "bash",
      "version": "5.1.16",
      "tty": 0
    }
  },
  {
    "type": "Display",
    "result": [
      {
        "id": 0,
        "name": "U2701B",
        "primary": false,
        "output": {
          "width": 3840,
          "height": 2160
        },
        "scaled": {
          "width": 0,
          "height": 0
        },
        "physical": {
          "width": 597,
          "height": 336
        },
        "refreshRate": 59.996624662466246,
        "rotation": 0,
        "bitDepth": 0,
        "hdrEnabled": false,
        "type": "Unknown"
      }
    ]
  },
  {
    "type": "DE",
    "error": "No DE found"
  },
  {
    "type": "WM",
    "error": "No WM found"
  },
  {
    "type": "WMTheme",
    "error": "WM Theme needs successful WM detection"
  },
  {
    "type": "Theme",
    "error": "No themes found"
  },
  {
    "type": "Icons",
    "error": "No icons could be found"
  },
  {
    "type": "Font",
    "error": "No fonts found"
  },
  {
    "type": "Cursor",
    "error": "Couldn't find cursor"
  },
  {
    "type": "Terminal",
    "result": {
      "processName": "xterm",
      "exe": "xterm",
      "exeName": "xterm",
      "exePath": "",
      "pid": 0,
      "ppid": 0,
      "prettyName": "xterm",
      "version": "",
      "tty": "/dev/pts/0"
    }
  },
  {
    "type": "TerminalFont",
    "result": {
      "font": {
        "name": "fixed",
        "size": "8.0",
        "styles": [],
        "pretty": "fixed (8.0pt)"
      },
      "fallback": {
        "name": "",
        "size": "",
        "styles": [],
        "pretty": ""
      }
    }
  },
  {
    "type": "CPU",
    "result": {
      "cpu": "Intel(R) Core(TM) i5-14600K",
      "vendor": "GenuineIntel",
      "cores": {
        "physical": 14,
        "logical": 20,
        "online": 20
      },
      "frequency": {
        "base": 3500,
        "max": 5300,
        "biosLimit": 0
      },
      "coreTypes": [],
      "temperature": null
    }
  },
  {
    "type": "GPU",
    "result": [
      {
        "index": null,
        "coreCount": null,
        "coreUsage": null,
        "memory": {
          "dedicated": {
            "total": null,
            "used": null
          },
          "shared": {
            "total": null,
            "used": null
          }
        },
        "driver": "nvidia (proprietary) 555.42.06",
        "name": "NVIDIA Device 2702 (VGA compatible)",
        "temperature": null,
        "type": "Unknown",
        "vendor": "NVIDIA",
        "platformApi": "",
        "frequency": 0,
        "deviceId": 114000
      },
      {
        "index": null,
        "coreCount": null,
        "coreUsage": null,
        "memory": {
          "dedicated": {
            "total": null,
            "used": null
          },
          "shared": {
            "total": null,
            "used": null
          }
        },
        "driver": "nvidia (proprietary) 555.42.06",
        "name": "NVIDIA Device 2702 (VGA compatible)",
        "temperature": null,
        "type": "Unknown",
        "vendor": "NVIDIA",
        "platformApi": "",
        "frequency": 0,
        "deviceId": 1000
      },
      {
        "index": null,
        "coreCount": null,
        "coreUsage": null,
        "memory": {
          "dedicated": {
            "total": null,
            "used": null
          },
          "shared": {
            "total": null,
            "used": null
          }
        },
        "driver": "i915",
        "name": "Intel Device A780 (VGA compatible)",
        "temperature": null,
        "type": "Integrated",
        "vendor": "Intel",
        "platformApi": "",
        "frequency": 1550,
        "deviceId": 20
      }
    ]
  },
  {
    "type": "Memory",
    "result": {
      "total": 67112202240,
      "used": 7103410176
    }
  },
  {
    "type": "Swap",
    "result": {
      "total": 2051010560,
      "used": 0
    }
  },
  {
    "type": "Disk",
    "result": [
      {
        "bytes": {
          "available": 248446504960,
          "free": 298343829504,
          "total": 980799373312,
          "used": 682455543808
        },
        "files": {
          "total": 60891136,
          "used": 2097974
        },
        "filesystem": "overlay",
        "mountpoint": "/",
        "mountFrom": "overlay",
        "name": "",
        "volumeType": [
          "Regular"
        ],
        "createTime": "2024-10-24T06:25:03.776+0000"
      }
    ]
  },
  {
    "type": "LocalIp",
    "result": [
      {
        "defaultRoute": true,
        "ipv4": "172.17.0.4/16",
        "ipv6": "",
        "mac": "",
        "name": "eth0",
        "mtu": -1,
        "speed": -1
      }
    ]
  },
  {
    "type": "Battery",
    "result": []
  },
  {
    "type": "PowerAdapter",
    "result": []
  },
  {
    "type": "Locale",
    "result": "C"
  },
  {
    "type": "Break",
    "error": "Unsupported for JSON format"
  },
  {
    "type": "Colors",
    "error": "Unsupported for JSON format"
  }
]
```

**Comment by aiwantaozi** [comment] 2024-10-24 07:04
Try several times, but couldn't reproduce.

**Comment by Finenyaco** [comment] 2024-10-24 07:44
It can be reproduced occasionally, and can be restored after restarting the container.

**Comment by aiwantaozi** [comment] 2024-10-24 08:54
Check the environment on the left where there are issues; it seems that nvidia-smi is problematic. The environment on the right is normal.  This the nvidia toolkit's issue, could be fixed by the solution provided by nvidia https://github.com/NVIDIA/nvidia-container-toolkit/issues/48.
<img width="1409" alt="image" src="https://github.com/user-attachments/assets/c2307bb8-d99c-4b2a-b77f-24f1b127149a">

**Comment by aiwantaozi** [comment] 2024-10-24 08:58
If this issue happens, try the solution provided by nvidia toolkit https://github.com/NVIDIA/nvidia-container-toolkit/issues/48

**Closed by aiwantaozi** 2024-10-24 08:58 UTC
Labels: bug-qa
